# Generated by Django 5.2.15 on 2026-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="new_field_1",
            field=models.TextField(blank=True),
        ),
    ]
