name: My First Github Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Run django migrations
      run: |
        python manage.py makemigrations --check

  run-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Run django migrations
      run: |
        python manage.py migrate