name: My First Github Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Run django migrations
      run: |
        python manage.py makemigrations --check

  run-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Run django migrations
      run: |
        python manage.py migrate

  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - run-migrations
      - check-migrations
    # if: github.ref == 'refs/head/main'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

